### ISSUE TITLE
Cesium new versions are not compatible

### ISSUE THREAD

**Issue by MarioPerezDev** [rulonder/cesium-sensors-es6#14]
cesium:^1.71 makes it install the latest inside this package, this leads to problems because cesium members deleted some files in the newest versions.

I think it should have cesium:1.71 as dependency instead, with no ^.

Consider testing it in 1.95

**Comment by rulonder** [comment]
New versions of cesium seem to have changed the shaders managements, will limit the version to 1.95

**Comment by rulonder** [comment]
try version 0.2.2
