### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by davesauce14** [rulonder/cesium-sensors-es6#30]
It seems support for sensors has been moved to a paid version of Cesium (Ion SDK) and the original opensource version of these utils has been moved to a private repo, will these plugins still work in the latest versions of Cesium?

I am not seeing any hits for these Entity rendering functions (conicSensor, customPatternSensor, and rectangularSensor.) in CesiumJS https://github.com/search?q=repo%3ACesiumGS%2Fcesium+rectangularSensor&type=code

Please let me know, thanks

**Comment by rulonder** [comment]
Hi Dave, This code is a fork of the sensors in cesium previous to the move to the paid version i.e. Cesium Ion. They can be used in cesiumJS without Ion SDK. Nevertheless, they still need to be aligned to webgl 2 for the very latest versions (part of the work on the shaders is already done).

**Comment by rulonder** [comment]
Shaders from version 1.0 are aligned to work with the latest cesium versions
